# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"setup": "00_eda.ipynb",
         "describe": "00_eda.ipynb",
         "savepath": "00_eda.ipynb",
         "plot": "00_eda.ipynb"}

modules = ["eda.py"]

doc_url = "https://lilacs2039.github.io/lileda/"

git_url = "https://github.com/lilacs2039/lileda/tree/master/"

def custom_doc_links(name): return None
